### ISSUE TITLE
git clone link requires authentication

### ISSUE THREAD

**Issue by dalekgamma** [JRansomed/cvelookup#1]
The "git clone" command in your README.MD points to  https://git.jransomed.com/jstevens/cvelookup.git - which required authentication
perhaps use https://github.com/JRansomed/cvelookup.git instead?

EDIT: apparently I can't spell.  Apologies

**Comment by JRansomed** [comment]
Fixing this, thanks for pointing it out.  I added this to github for my co-workers to access it.  I hadn't realized anyone else found it.  I'll have to look into notifications on this.  Sorry about neglecting this.
